sudo: required
language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      env: CXX=g++
    - os: linux
      dist: trusty
      env: CXX=clang++
    - os: osx
      env: CXX=clang++
notifications:
  email:
    on_success: always
    on_failure: always
script:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then export NODE_LABELS="Linux Ubuntu Ubuntu-14.04"; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then export NODE_LABELS="OSX OSX-10.9"; fi
  - echo $NODE_LABELS
  - ./.jenkins
